Frontend initial
tosha-220/NgShop pull request #10
Opened 2017-02-14 17:14 UTC by tosha-220

2017-02-16 23:24 UTC, kykint requested changes
Надо убрать все лишние файлы (jsки)

2017-02-16 23:24 UTC, kykint commented on Frontend/src/app/app.component.js
> +"use strict";
Этого файла быть не должно в репо. Вообще скомпиленных файлов быть не должно. Этот файл союирается из ts-ки

2017-02-17 10:16 UTC, kykint requested changes
Frontend/frontend.txt - этот файл не нужен тоже

2017-02-17 10:16 UTC, kykint commented on Frontend/src/app/app.component.ts
> +  template: `<h1>Hello {{name}}</h1>`,
Выноси шаблон сразу в отдельный html файл

2017-02-17 10:16 UTC, kykint commented on Frontend/src/systemjs.config.extras.js
> +/**
Этот файл нужен?

2017-02-17 11:01 UTC, tosha-220 commented on Frontend/src/systemjs.config.extras.js
> +/**
Сам не знаю, просто в quickstart он есть

2017-02-17 11:05 UTC, tosha-220 commented on Frontend/src/app/app.component.ts
> +  template: `<h1>Hello {{name}}</h1>`,
Frontend/frontend.txt его в последнем коммите не было уже

2017-02-17 11:06 UTC, kykint commented on Frontend/src/systemjs.config.extras.js
> +/**
ну если не нужен, то надо удалять и убирать ссылку на него

2017-02-17 11:07 UTC, kykint commented on Frontend/src/app/app.component.ts
> +  template: `<h1>Hello {{name}}</h1>`,
txt я  понял. Но шаблон вынести надо

2017-02-17 11:13 UTC, tosha-220 commented on Frontend/src/app/app.component.ts
> +  template: `<h1>Hello {{name}}</h1>`,
хорошо

2017-02-17 11:42 UTC, kykint approved these changes

2017-02-17 17:08 UTC, Mihail-Vilms-MSU approved these changes
ok

2017-02-18 10:00 UTC, merged