Added service with json
tosha-220/NgShop pull request #16
Opened 2017-02-18 13:56 UTC by tosha-220

2017-02-18 20:58 UTC, kykint requested changes

2017-02-18 20:58 UTC, kykint commented on Frontend/src/app/app.component.ts
> +import { Component,OnInit} from '@angular/core';
Ctrl + Alt + L - форматирование кода!

2017-02-18 20:58 UTC, kykint commented on Frontend/src/app/app.service.ts
> +    return this.http.get("http://localhost:8080/greeting")
не вызывай toPromise - оставляй Observable - лучше с ними работать

2017-02-18 20:58 UTC, kykint commented on Frontend/src/app/app.component.ts
> +  value=["offline"];
странное значение по-умолчанию. быть может должно быть {value: "offline"}?

2017-02-19 08:07 UTC, tosha-220 commented on Frontend/src/app/app.service.ts
> +    return this.http.get("http://localhost:8080/greeting")
т.е возвращать Observable, и в главном классе вызывать toPromise или вообще работать с одним Observable?

2017-02-19 13:11 UTC, kykint commented on Frontend/src/app/app.service.ts
> +    return this.http.get("http://localhost:8080/greeting")
не надо toPromise - прямо у Observable есть метод subscribe

2017-02-19 21:20 UTC, kykint requested changes

2017-02-19 21:20 UTC, kykint commented on Frontend/src/app/app.service.ts
> +    return this.http.get("http://localhost:8080/");
лучше здесь вызвать .map() для маппинга json и возвращать не `Observable<Response>`а `Observable<MyInterface>`. Интерфейс описать и положить отдельным файлом.

2017-02-19 21:21 UTC, kykint commented on Frontend/src/app/app.service.ts
> +    return this.http.get("http://localhost:8080/");
https://angular.io/docs/ts/latest/tutorial/toh-pt6.html#!#-_observable-s

2017-02-20 13:12 UTC, kykint approved these changes

2017-02-21 07:56 UTC, kykint commented on Frontend/src/app/app.service.ts
> +    return this.http.get("http://localhost:8080/").map(res => res.json());
http://localhost:8080/ -адрес захардкожен - надо вынести в отдельные настройки

2017-02-21 12:23 UTC, Mihail-Vilms-MSU approved these changes

2017-02-21 15:05 UTC, merged