List of products added, details by clicking on product
tosha-220/NgShop pull request #21
Opened 2017-02-28 15:18 UTC by tosha-220

2017-03-01 22:04 UTC, kykint requested changes

2017-03-01 22:04 UTC, kykint commented on Frontend/src/app/app.component.html
> +<nav>
навигацию лучще сразу вынести в отдельный компонент

2017-03-01 22:04 UTC, kykint commented on Frontend/src/app/common.ts
> +export const listUrl: string = "http://localhost:8080/products";
адрес бекенда должен подгружаться из внешнего файла, в рантайме (перед инициализацией). Могу подсказать завтра как это лучше сделать

2017-03-01 22:04 UTC, kykint commented on Frontend/src/app/product.service.ts
> +export class ProductService {
нет обработки http ошибок

2017-03-01 22:04 UTC, kykint commented on Frontend/src/app/product/product.component.html
> +<!DOCTYPE html>
тут не должно быть ни head ни body!!

2017-03-01 22:04 UTC, kykint commented on Frontend/src/app/products/products.component.html
> +<!DOCTYPE html>
и тут не должно быть ни head ни body

2017-03-02 13:18 UTC, tosha-220 commented on Frontend/src/app/product.service.ts
> +export class ProductService {
почему то не получается обработать эту ошибку в методе subscribe

2017-03-02 15:17 UTC, kykint commented on Frontend/src/app/product.service.ts
> +export class ProductService {
какую ошибку? при чем тут subscribe? Вот пример (скопировал из свое  приложения)
`return this.http.post(url, body)
            .map(this.extractData)
            .catch(this.handleError);`

2017-03-02 17:34 UTC, tosha-220 commented on Frontend/src/app/product.service.ts
> +export class ProductService {
я просто пытался поймать исключение вот таким способом, но чет не получилось
return this.http.request(request)
  .map(res => res.json())
  .subscribe(
    data => console.log(data),
    err => console.log(err),
  );

2017-03-03 16:19 UTC, kykint commented on Frontend/src/app/product.service.ts
> +export class ProductService {
а зачем так то? лови через .catch

2017-03-10 14:18 UTC, tosha-220 commented
ну как оно?

2017-03-10 15:09 UTC, kykint commented on Frontend/src/app/app.component.html
> +<nav>
nav не вынес

2017-03-10 15:10 UTC, kykint commented on Frontend/src/app/common.ts
> +export const listUrl: string = "http://localhost:8080/products";
не удалено

2017-03-10 15:10 UTC, kykint commented on Frontend/src/app/product/product.component.html
> +<!DOCTYPE html>
аналогично все на месте

2017-03-10 15:11 UTC, kykint commented
не все поправлено

2017-03-10 15:12 UTC, kykint commented
и помоги, пожалуйста, Михаилу с заводом бекенда - он должен работать по оставленной мной инструкции

2017-03-12 12:56 UTC, kykint approved these changes

2017-03-12 12:59 UTC, Mihail-Vilms-MSU approved these changes

2017-03-12 13:00 UTC, merged