Mihav
tosha-220/NgShop pull request #8
Opened 2017-02-13 17:09 UTC by Mihail-Vilms-MSU

как то так 1.0.0.0.1

2017-02-13 23:47 UTC, kykint requested changes
надо поправить

2017-02-13 23:47 UTC, kykint commented on Backend/src/main/java/net/ckr/shop/HomeController.java
> +//import java.text.DateFormat;
лишний код не комментим, а удаляем. Вообще импорты автоматически ненужные удаляются по Ctrl+Alt+L в IDEA

2017-02-13 23:47 UTC, kykint commented on Backend/src/main/webapp/WEB-INF/views/home.jsp
> +<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
этого файла быть не должно. webapp вообще не нужен

2017-02-14 15:14 UTC, kykint commented on Backend/src/main/java/net/ckr/shop/HomeController.java
> +		//DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.LONG, locale);
Убери лишние комменты

2017-02-14 15:15 UTC, Mihail-Vilms-MSU commented on Backend/src/main/java/net/ckr/shop/HomeController.java
> +		//DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.LONG, locale);
ок

2017-02-16 23:20 UTC, kykint requested changes
Надо поправить, чтобы это собиралось

2017-02-16 23:20 UTC, kykint commented on Backend/src/main/java/net/ckr/shop/HomeController.java
> +<<<<<<< HEAD
Судя по всему тут merge conflict ты забыл разрезолвить. Поправь, это явно не собирается

2017-02-16 23:20 UTC, kykint commented on Backend/src/main/java/net/ckr/shop/HomeController.java
> +		//DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.LONG, locale);
лишние комменты остались

2017-02-16 23:20 UTC, kykint commented on Backend/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
> +<<<<<<< HEAD
Тоже конфликт

2017-02-17 15:02 UTC, kykint requested changes

2017-02-17 15:02 UTC, kykint commented on Backend/src/main/java/net/ckr/shop/HomeController.java
> +
Код должен быть отформатирован

2017-02-19 13:18 UTC, kykint requested changes

2017-02-19 13:18 UTC, kykint commented on Backend/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
> +	//<beans:bean class="org.springframework.web.servlet.view.InternalResourceViewResolver">
Что это такое? Видимо быть не должно

2017-02-19 17:45 UTC, kykint requested changes

2017-02-19 17:45 UTC, kykint commented on Backend/src/main/java/net/ckr/shop/HomeController.java
> +package net.ckr.shop;
"ckb этот файл не нужен, то его надо удлать из ветки перед мержем

2017-02-19 17:45 UTC, kykint commented on Backend/src/main/java/netckr/shop/Pojos/hwpojo.java
> +		super();
здесь super() не имеет смысла
И код опять не отформатирован!

2017-02-19 21:06 UTC, Mihail-Vilms-MSU commented on Backend/src/main/java/netckr/shop/Pojos/hwpojo.java
> +		super();
всё понял, обязательно исправлю.

2017-02-20 13:13 UTC, kykint commented on Backend/src/main/java/net/ckr/shop/HomeController.java
> +package net.ckr.shop;
Поправишь?

2017-02-20 14:01 UTC, Mihail-Vilms-MSU commented on Backend/src/main/java/net/ckr/shop/HomeController.java
> +package net.ckr.shop;
ок, понял, сделаю

2017-02-21 07:52 UTC, kykint approved these changes

2017-02-21 10:03 UTC, tosha-220 approved these changes

2017-02-21 10:51 UTC, merged